name: Release

on:
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown

      - name: Build WASM
        run: cargo build --profile wasm-release --target wasm32-unknown-unknown

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      
      - name: Install wasm-bindgen
        run: cargo binstall -y wasm-bindgen-cli

      - name: Bundle WASM
        run: |
          wasm-bindgen --out-dir ./wasm/ --target web --no-typescript ./target/wasm32-unknown-unknown/wasm-release/grenouille.wasm
          cp -r assets/ wasm/assets/

      - name: Upload Page Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: wasm/
